name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - run: npm ci

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_sE6n6vAwiTr4EapoArEemenU
          VERCEL_PROJECT_ID: prj_RRmVH8A84VAI8WeLnTNYDudyil8K
